<?php

namespace App\Providers;

use Illuminate\Support\Facades\Event;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        'App\Events\Event' => [
            'App\Listeners\EventListener',
        ],
    ];

    /**
     * Register any events for your application.
     * perform post-registration booting of services
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
        view()->composer('view',function (){

        });
        //
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
